### ISSUE TITLE
do you plan the implementation of text insertion?

### ISSUE THREAD

**Issue by fabersheep** [pwambach/angular-canvas-painter#10]
I think it would be nice some basic text support, something like right-click/insert text here, nothing more. 
The text font and size could be configured in the options object.

**Comment by pwambach** [comment]
hey, no sorry, the directive is only meant to be a painting helper, not a complete image editor tool. You could add another directive on top which makes text insertion possible. But i would rather suggest to not paint the text into the canvas image but to use overlays which display the text at a specified position. This gives you the ability to work with the text (like search and edit it) in the future instead of rastarizing it

cheers
Phil
